openapi: 3.0.0
info:
  title: Restaurant API
  description: API for retrieving restaurant products and categories
  version: 1.0.0
servers:
  - url: https://api.restaurant.com/v1
paths:
  /products:
    get:
      summary: Get products
      description: Retrieve a list of products
      tags:
        - Products API
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsListResponse'
  /categories:
    get:
      summary: Get categories
      description: Retrieve a list of product categories
      tags:
        - Categories API
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriesListResponse'
components:
  schemas:
    Product:
      type: object
      description: Product information
      properties:
        name:
          type: string
          description: Product name
          example: "Bacon Cheeseburger"
        sku:
          type: string
          description: Product SKU
          example: "P-BC-001"
        price:
          type: number
          description: Product price in cents without decimals
          example: 1295
        image:
          type: string
          description: Product image URL
          example: "https://example.com/images/bacon_cheeseburger.jpg"
        category:
          type: string
          description: Product category
          example: "Burgers"
        variations:
          type: array
          description: Product variations
          items:
            $ref: '#/components/schemas/Variation'
    Variation:
      type: object
      description: Variation information
      properties:
        name:
          type: string
          description: Variation name
          example: "Sauce"
        max_selection:
          type: integer
          description: Maximum number of items that can be selected
          example: 2
        mandatory:
          type: boolean
          description: Whether the variation is mandatory
          example: true
        items:
          type: array
          description: Items inside the variation
          items:
            $ref: '#/components/schemas/VariationItem'
    VariationItem:
      type: object
      description: Variation item information
      properties:
        name:
          type: string
          description: Variation item name
          example: "Ketchup"
        sku:
          type: string
          description: Variation item SKU
          example: "V-K-001"
        price:
          type: number
          description: Variation item price in cents without decimals
          example: 50
    ProductsListResponse:
      type: object
      description: List of retrieved products
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Category:
      type: object
      description: Category information
      properties:
        name:
          type: string
          description: Category name
          example: "Burgers"
        image:
          type: string
          description: Category image URL
          example: "https://example.com/images/burgers.jpg"
    CategoriesListResponse:
      type: object
      description: List of retrieved categories
      properties:
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'