/**
 * API BHB Customer Backend
 * API BHB Customer Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Image } from "./image";

/**
 * Category information
 */
export interface Category {
  /**
   * Category name
   */
  id?: string;
  name?: string;
  image?: string;
  order?: number;
  location_id?: string;
}
