/**
 * API BHB Customer Backend
 * API BHB Customer Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Option } from "./option";

/**
 * Modifier information
 */
export interface Modifier {
  /**
   * Modifier id
   */
  id?: string;
  /**
   * Modifier name
   */
  name?: string;
  /**
   * Modifier type
   */
  type?: Modifier.TypeEnum;
  /**
   * Modifier selection
   */
  selection?: Modifier.SelectionEnum;
  /**
   * Minimum number of options the customer must select for this modifier group on this item (from Square item rules).
   */
  minSelections?: number;
  /**
   * Maximum number of options the customer may select for this modifier group on this item (from Square item rules).
   */
  maxSelections?: number;
  options?: Array<Option>;
  quantity?: number;
}
export namespace Modifier {
  export type TypeEnum = "LIST";
  export const TypeEnum = {
    LIST: "LIST" as TypeEnum,
  };
  export type SelectionEnum = "SINGLE" | "MULTIPLE";
  export const SelectionEnum = {
    SINGLE: "SINGLE" as SelectionEnum,
    MULTIPLE: "MULTIPLE" as SelectionEnum,
  };
}
