/**
 * API BHB Customer Backend
 * API BHB Customer Backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Option } from './option';

/**
 * Modifier information
 */
export interface Modifier { 
    /**
     * Modifier id
     */
    id?: string;
    /**
     * Modifier name
     */
    name?: string;
    /**
     * Modifier type
     */
    type?: Modifier.TypeEnum;
    /**
     * Modifier selection
     */
    selection?: Modifier.SelectionEnum;
    options?: Array<Option>;
}
export namespace Modifier {
    export type TypeEnum = 'LIST';
    export const TypeEnum = {
        LIST: 'LIST' as TypeEnum
    };
    export type SelectionEnum = 'SINGLE' | 'MULTIPLE';
    export const SelectionEnum = {
        SINGLE: 'SINGLE' as SelectionEnum,
        MULTIPLE: 'MULTIPLE' as SelectionEnum
    };
}