/**
 * API BHB Customer Backend
 * API BHB Customer Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Information about order operational
 */
export interface Operation {
  /**
   * Operation identifier
   */
  id?: string;
  /**
   * Expected ready timestamp. Usually 15 mins after order is created.
   */
  createdTs?: number;
  /**
   * Expected delivery timestamp. Usually 30 mins after order is created.
   */
  expectedReadyTs?: number;
  /**
   * Expected delivery timestamp. Usually 30 mins after order is created.
   */
  expectedDeliveredTs?: number;
  /**
   * Expected total order timestamp. Usually 15 mins after order is created, 30 mins for delivery orders.
   */
  expectedTotalOrderTs?: number;
  /**
   * Total time of the order in the kitchen in miliseconds
   */
  kitchenTime?: number;
  /**
   * Total time of the order during delivery in miliseconds
   */
  inDeliveryTime?: number;
  /**
   * Total time of the order (kitchen + delivery) in miliseconds
   */
  totalOrderTime?: number;
}
