/**
 * API BHB Customer Backend
 * API BHB Customer Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Option information
 */
export interface Option {
  /**
   * Option id
   */
  id?: string;
  /**
   * Default option
   */
  defaultOption?: boolean;
  /**
   * Option name
   */
  name?: string;
  /**
   * Option price in cents without decimals
   */
  price?: number;
}
