/**
 * API BHB Customer Backend
 * API BHB Customer Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CouponDto } from "src/dto/coupon.dto";
import { Customer } from "./customer";
import { Product } from "./product";
import { Status } from "./status";
import { ClaimRewardDto } from "src/dto/claim-reward.dto";

/**
 * Order information
 */
export interface Order {
  /**
   * Order id
   */
  id?: string;
  /**
   * Order creation date
   */
  date?: string;
  /**
   * Indicates if it is an scheduled order
   */
  scheduled?: boolean;
  /**
   * Order type
   */
  type?: Order.TypeEnum;
  /**
   * Order amount in cents without decimals
   */
  amount?: number;
  /**
   * Order notes
   */
  notes?: string;
  customer?: Customer;
  products?: Array<Product>;
  status?: Status;
  statuses?: Array<Status>;
  locationId?: string;
  coupon?: CouponDto;
  reward?: ClaimRewardDto;
}

export namespace Order {
  export type TypeEnum = "Delivery" | "Pickup" | "Dinein";
  export const TypeEnum = {
    Delivery: "Delivery" as TypeEnum,
    Pickup: "Pickup" as TypeEnum,
    Dinein: "Dinein" as TypeEnum,
  };
}
