/**
 * API BHB Customer Backend
 * API BHB Customer Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from "./category";
import { Image } from "./image";
import { Modifier } from "./modifier";

/**
 * Product information
 */
export interface Product {
  /**
   * Product id
   */
  id?: string;
  /**
   * Product catalog id
   */
  catalogId?: string;
  /**
   * Product name
   */
  name?: string;
  /**
   * Product description
   */
  description?: string;
  /**
   * Product price
   */
  price?: number;
  categoryId?: string;
  /**
   * Product image
   */
  images?: Array<Image>;
  modifiers?: Array<Modifier>;
  quantity?: number;
}
